# ------------------------------------------------------------------------------
# Author: dorsa007
# Created: 2026-04-21
# ------------------------------------------------------------------------------
blueprint:
  name: FVE - Disable Overflow
  description: 'Disables overflow when eletricity price is negative (Export Limit is set to 0). When the spot price is positive again, script sets Export Limit back to entered Value.'
  domain: automation
  input:
    spot_price:
      name: Energy Spot Price
      description: Actual energy spot price entity
      selector:
        entity:
          filter:
            #domain: sensor
            domain: input_number
    goodwe_export_limit:
      name: GoodWe Export Limit
      description: Inverter export limit target entity
      selector:
        target:
          entity:
            domain: number
            #integration: goodwe
    export_limit_value:
      name: Export Limit Value (W)
      description: |
        Numeric value of the original export limit (W) which is set when the price is positive again
        - if you don't set this value even if your Export Limit entity uses Watts, default value is 5500 W
      default: 5500
      selector:
        number:
          min: 0
          max: 5500
          step: 100
          unit_of_measurement: 'W'
          mode: slider
    spot_price_export_limit:
      name: Spot Price Export Limit (Kc/MWh)
      description: |
        Spot price threshold (in Kc/MWh) for setting export limit to 0
      default: 0
      selector:
        number:
          min: 0
          max: 1000
          step: 1
          unit_of_measurement: 'Kc/MWh'
          mode: box

variables:
  spot_price: !input spot_price
  goodwe_export_limit: !input goodwe_export_limit
  export_limit_value: !input export_limit_value
  spot_price_export_limit: !input spot_price_export_limit
triggers:
- trigger: numeric_state
  entity_id: !input spot_price
  below: !input spot_price_export_limit
conditions: []
actions:
#- action: number.set_value
- action: input_number.set_value
  target: !input goodwe_export_limit
  data:
    value: 0
- sequence:
  - wait_template: '{{ states(spot_price) | float(default=0) > states(spot_price_export_limit) }}'
  #- action: number.set_value
  - action: input_number.set_value
    target: !input goodwe_export_limit
    data:
      value_template: >-
        {{ export_limit_value }}
mode: single
